### PR TITLE
`warp` service improvements

### PR DESCRIPTION
**Pull request by crinklywrappr**
## simplify customization & testing
Adds the following options

- package
- user
- group

## certificate
Simplifies certificate installation described [in the docs](https://developers.cloudflare.com/cloudflare-one/connections/connect-devices/warp/install-cloudflare-cert/#nix-and-nixos).

## udpPort & openFirewall
Simplifies firewall configuration using the same `openFirewall` nomenclature used w/ [many other services](https://search.nixos.org/options?query=openFirewall) including ssh.  This is useful for some users because warp binds to UDP port 2408.  However, users can also specify one of the fallback ports described [in the docs](https://developers.cloudflare.com/cloudflare-one/connections/connect-devices/warp/deployment/firewall#warp-udp-ports), 

## refined the systemd service unit
I used the approach described in [this forum post](https://discourse.nixos.org/t/using-cloudflared-with-zero-trust-dashboard-on-nixos/19069/8?u=daf).

### CODE REVIEW

**Comment by WolfangAukang** [comment]
Sorry for taking too long into considering this @crinklywrappr. Just a question, is it possible to use another package with this service besides `cloudflare-wrap`?

**Comment by crinklywrappr** [comment]
Sure is. Eventually users will want to enable the version in unstable, for instance.

**Comment by WolfangAukang** [comment]
Okay, fair enough. Going to add it.

**Comment by WolfangAukang** [comment]
I have added your changes to the PR

**Pull request closed without merging**
